name: 'pr-size-labelator'
description: 'Label a pull request based on number of lines modified'
inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  xs_limit:
    description: 'Max value for a extra small PR'
    required: false
    default: '20'
  sm_limit:
    description: 'Max value for a small PR'
    required: false
    default: '50'
  md_limit:
    description: 'Max value for a medium PR'
    required: false
    default: '200'
  lg_limit:
    description: 'Max value for a large PR'
    required: false
    default: '500'
  custom_tag_xs:
    description: 'Custom tag to be written for extra small PR'
    required: false
    default: 'size-sm'
  custom_tag_sm:
    description: 'Custom tag to be written for small PR'
    required: false
    default: 'size-sm'
  custom_tag_md:
    description: 'Custom tag to be written for medium PR'
    required: false
    default: 'size-sm'
  custom_tag_lg:
    description: 'Custom tag to be written for large PR'
    required: false
    default: 'size-sm'
  custom_tag_xl:
    description: 'Custom tag to be written for extra large PR'
    required: false
    default: 'size-sm'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.GITHUB_TOKEN}}
    - ${{inputs.xs_limit}}
    - ${{inputs.sm_limit}}
    - ${{inputs.md_limit}}
    - ${{inputs.lg_limit}}
    - ${{inputs.custom_tag_xs}}
    - ${{inputs.custom_tag_sm}}
    - ${{inputs.custom_tag_md}}
    - ${{inputs.custom_tag_lg}}
    - ${{inputs.custom_tag_xl}}
